Week2
basafilm/serverless pull request #2
Opened 2021-09-16 12:16 UTC by basafilm

2021-09-18 08:09 UTC, pdsorensen requested changes
Hi @basafilm , the PR is hard to review as the whole template is part of it. I suggest you finish the two assignments I commented, and then we can take care of the front end together in class. 

Cheers, great work!

2021-09-18 08:09 UTC, pdsorensen commented on week2/materials/homework/assignments.md
> +use case: `?`
Please write a use case. 👍

2021-09-18 08:09 UTC, pdsorensen commented on week2/materials/homework/assignments.md
> +brief description: `Clean up incomplete multipart uploads.`
Great overview!

2021-09-18 08:09 UTC, pdsorensen commented on week2/materials/homework/assignments.md
> +brief description of favourite security feature: `enable Server-side encryption settings`
Indeed, a very useful feature! Default encryption/safety with a single click.

2021-09-26 13:27 UTC, bytewiz approved these changes
Looks good to me 👍

2021-09-26 13:29 UTC, bytewiz approved these changes
Looks good to me 👍

2021-09-26 13:29 UTC, bytewiz commented on week2/materials/homework/assignments.md
Would be nice to add the actual total price of 51TB here based on the the pricing you have above

51TB = ?

2021-09-26 20:12 UTC, merged